### PR TITLE
Clean up temporary file/folder after usage

### LINKED ISSUE #24: Clean up /tmp/david after usage
I believe it isn't needed after execution so it can be cleaned up in the bash script.

### PR DESCRIPTION
**Pull request by shingz96**
Try to fix #24 & #27

### CODE REVIEW

**Review by angelbarrera92 — APPROVED** [review]

**Comment by angelbarrera92** [comment]
What about windows script?

**Comment by shingz96** [comment]
for window script seem no create temporary folder explicitly, not sure can apply the same like bash script

**Comment by angelbarrera92** [comment]
You can remove the downloaded binary in windows script

;)

**Comment by shingz96** [comment]
> You can remove the downloaded binary in windows script
> 
> ;)

applied to window scripts

**Comment by angelbarrera92** [comment]
Hoff approves

**Comment by angelbarrera92** [comment]
@shingz96 add yourself as contributor in CONTRIBUTORS.md file. Feel free to open a new pull request

**Pull request merged**
