### PR TITLE
WIP: add windows cmd option

### LINKED ISSUE #11: Make a windows script as linux ones
This project needs an automatic script, like the one that works for linux and mac, to make it easier to run on windows operating systems. 

As you can see, in linux and macos operating systems, with a simple command you can download and run the binary. 
```bash
curl -L http://tiny.cc/hasselhoff | bash
```
As a requirement must be a single command line and that the procedure is as fast as possible. This must be documented in the README.md. 

It must be compatible with Windows 7 or later.

### PR DESCRIPTION
**Pull request by guumaster**
This is the easiest way I've found. I'll work on Windows 10 because it comes with curl installed.

Don't merge until you register a new tiny.cc url like `https://tiny.cc/win-hasselhoffme`, if you register a different one let me know so I can change the PR. 

Close #11

### CODE REVIEW

**Comment by guumaster** [comment]
I hope this make The Hasselhoff happy :)

happy hasselhoff

**Comment by guumaster** [comment]
You can try on windows without the tiny.cc url with this cmd:

`curl -s -L https://raw.githubusercontent.com/guumaster/hasselhoffme/master/hasselhoff.cmd  --output hass.cmd && hass.cmd`

**Comment by angelbarrera92** [comment]
Good morning @guumaster 
I have to see, it is working perfect on a Windows 10 laptop. I will request the tiny.cc domain and this merge request will be merged!

```bash
curl -s -L https://raw.githubusercontent.com/guumaster/hasselhoffme/master/hasselhoff.cmd | cmd
```

Thanks!

**Comment by angelbarrera92** [comment]
Now, we have 
`http://tiny.cc/win-hasselhoff`
and
`http://tiny.cc/win-hasselhoffme`

I will do some changes (Readme) and merge it! 
Thanks @guumaster

**Review by angelbarrera92 — APPROVED** [review]
👌

**Pull request merged**
