### PR TITLE
PR for Issue #28 - Include go report in the README.md

### PR DESCRIPTION
**Pull request by BigOokie**
Changes to Readme.md:
- Added Go Report Card badge for the project
- Fixed some typos
- Added section for cloning and building the project locally (including running dep ensure to pull dependencies).

Addressing issues identified by Go Report Card can be done under another PR I believe.

### CODE REVIEW

**Comment by BigOokie** [comment]
This PR addresses issue #28

**Comment by angelbarrera92** [comment]
Again @BigOokie awesome work. 

Changes Approves

**Comment by angelbarrera92** [comment]
@BigOokie feel free to add yourself to CONTRIBUTORS.md file
Make it funny!

**Comment by BigOokie** [comment]
> @BigOokie feel free to add yourself to CONTRIBUTORS.md file
> Make it funny!

Cheers. Will do

**Comment by BigOokie** [comment]
Check PR #34

**Pull request merged**
